version: "3"
services:
  outline_redis:
    container_name: 'outline_redis'
    image: redis
    command: redis-server --appendonly yes
  outline_db:
    container_name: 'outline_db'
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=outline
      - PGDATA=/pgdata
    volumes:
      - ./data/postgresql:/pgdata
  outline:
    container_name: 'outline'
    image: outline:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pull: 1
    links:
      - outline_db
      - outline_redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@outline_db/outline
      - REDIS_URL=redis://outline_redis:6379
    command: yarn dev
    ports:
      - "3000:3000"
